swagger: "2.0"
info:
    title: Data application proxy
    description: A service for proxing requests/authorization to data applications using Keboola components.
    version: "1.0"
host: hub.keboola.com
consumes:
    - application/json
produces:
    - application/json
paths:
    /_proxy/api/:
        get:
            tags:
                - appsproxy
            summary: Redirect to /_proxy
            description: Redirect to /_proxy.
            operationId: ApiRootIndex
            responses:
                "301":
                    description: Moved Permanently response.
            schemes:
                - https
    /_proxy/api/v1:
        get:
            tags:
                - documentation
            summary: List API name and link to documentation.
            description: List API name and link to documentation.
            operationId: ApiVersionIndex
            responses:
                "200":
                    description: OK response.
                    schema:
                        $ref: '#/definitions/ServiceDetail'
                        required:
                            - api
                            - documentation
            schemes:
                - https
    /_proxy/api/v1/documentation/openapi.json:
        get:
            tags:
                - documentation
            summary: Swagger 2.0 JSON Specification
            operationId: OpenapiJson
            responses:
                "200":
                    description: File downloaded
                    schema:
                        type: file
            schemes:
                - http
                - https
    /_proxy/api/v1/documentation/openapi.yaml:
        get:
            tags:
                - documentation
            summary: Swagger 2.0 YAML Specification
            operationId: OpenapiYaml
            responses:
                "200":
                    description: File downloaded
                    schema:
                        type: file
            schemes:
                - http
                - https
    /_proxy/api/v1/documentation/openapi3.json:
        get:
            tags:
                - documentation
            summary: OpenAPI 3.0 JSON Specification
            operationId: Openapi3Json
            responses:
                "200":
                    description: File downloaded
                    schema:
                        type: file
            schemes:
                - http
                - https
    /_proxy/api/v1/documentation/openapi3.yaml:
        get:
            tags:
                - documentation
            summary: OpenAPI 3.0 YAML Specification
            operationId: Openapi3Yaml
            responses:
                "200":
                    description: File downloaded
                    schema:
                        type: file
            schemes:
                - http
                - https
    /_proxy/api/v1/validate:
        get:
            tags:
                - appsproxy
            summary: Validation of OIDC authorization provider configuration
            description: Validation endpoint of OIDC authorization provider configuration.
            operationId: Validate
            responses:
                "200":
                    description: OK response.
                    schema:
                        $ref: '#/definitions/Validations'
            schemes:
                - https
            security:
                - storage-api-token: []
definitions:
    Configuration:
        title: Configuration
        type: object
        properties:
            clientID:
                type: string
                description: Client ID of provider.
                example: github.oidc
            clientSecret:
                type: string
                description: Client secret provided by OIDC provider.
                example: thisissupersecret
            id:
                type: string
                description: Unique ID of provider.
                example: oidc#1
        description: The configuration that is part of the auth providers section.
        example:
            clientID: github.oidc
            clientSecret: thisissupersecret
            id: oidc#1
        required:
            - id
            - clientID
            - clientSecret
    ServiceDetail:
        title: ServiceDetail
        type: object
        properties:
            api:
                type: string
                description: Name of the API
                example: appsproxy
            documentation:
                type: string
                description: URL of the API documentation.
                example: https://appsproxy.keboola.com/v1/documentation
        example:
            api: appsproxy
            documentation: https://appsproxy.keboola.com/v1/documentation
        required:
            - api
            - documentation
    Validations:
        title: Validations
        type: object
        properties:
            configuration:
                type: array
                items:
                    $ref: '#/definitions/Configuration'
                description: All authorization providers.
                example:
                    - exampleerrordata:
                        statusCode: 404
                        error: validations incorrect
                        message: unable to validate due to missing entry
                      id: test
                      name: My Template
        example:
            configuration:
                - exampleerrordata:
                    statusCode: 404
                    error: validations incorrect
                    message: unable to validate due to missing entry
                  id: test
                  name: My Template
securityDefinitions:
    storage-api-token:
        type: apiKey
        description: Storage Api Token Authentication.
        name: X-StorageApi-Token
        in: header
